### ISSUE TITLE
Kolom komentar tidak aktif?

### ISSUE THREAD

**Issue by viechoco** [ditatompel/insights#15]
Kalau dari tempat aku, ada tombol untuk komentar, tapi waktu di klik cuma turun ke halaman paling bawah dan tidak ada kolom komentar. Cuma aku atau memang begitu?

**Comment by jasmerah1966** [comment]
Kynya emang ga diaktifin sama @ditatompel 
Bukannya mending diaktifin om?

**Comment by ditatompel** [comment]
> Bukannya mending diaktifin om?

Sure, go ahead.
Choices:
- https://averagelinuxuser.com/staticman-comments/
- https://giscus.app/
- https://utteranc.es/
- https://disqus.com/

Masing2 ada kelebihan & kekurangan, mau yg mana? @viechoco @jasmerah1966 

Note: Untuk _self-hosted_ commento ngga dulu aja, krn baik commento dan commento++ sepertinya lama ga ada update. Biar komentar di blog Ghost yg lama ilang gpp. Haha.

**Comment by viechoco** [comment]
Giscus sama utterances sepertinya cuma bisa pake Github ya? klo aku sih prefer Disqus

**Comment by jasmerah1966** [comment]
Giscus oke juga klo buat gw om dit

**Comment by viechoco** [comment]
Oke ka, boleh juga. baru tahu ada fitur discussionnya di github
