### ISSUE TITLE
Do not generate all RSS feeds?

### ISSUE THREAD

**Issue by jasmerah1966** [ditatompel/insights#48]
**Is your feature request related to a problem? Please describe.**
When the article / post grows, RSS feed items will also grow.

**Describe the solution you'd like**
Limiting last `x` posts to be generated in RSS feeds may be the solution.

**Comment by ditatompel** [comment]
Yes, seems possible using `rssLimit` on hugo config file and applied on https://github.com/ditatompel/insights/commit/4417bac6894ed174e3e9c8772fdaa060e5ce3e0d.
